---
- name: Creating users
  user:
    name: "{{ item.name }}"
    state: present
    shell: /bin/bash
    generate_ssh_key: yes
    group: "{{ item.primary_group | default(item.name) }}"
    groups: "{{ item.groups | default('') }}"
  with_items: "{{ users_list }}"

- name: Authorize access
  authorized_key: "user={{ item.0.name }} key='{{ lookup('file', item.1) }}'"
  with_subelements:
    - "{{ users_list }}"
    - authorized
