---
# Reference: https://github.com/geerlingguy/ansible-role-mysql

- name: Add repository
  apt_repository: "repo='deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/{{ mariadb_version }}/ubuntu trusty main' state=present"

- name: Add repository key
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db

- name: Check if installed
  stat: path=/etc/init.d/mysql
  register: mariadb_installed

- name: Update apt cache
  apt: update_cache=yes
  when: mariadb_installed.stat.exists == false

- name: Installation
  apt: "pkg={{ item }} state=present"
  with_items:
    - mariadb-server
    - mariadb-client

- name: Installation of Python libraries
  apt: name=python-mysqldb state=present

- include: cleanup.yml
  when: mariadb_installed.stat.exists == false

- name: Start on boot
  service: name=mysql state=started enabled=yes

- include: secure.yml
- include: users.yml
- include: databases.yml
