---

- name: Add PHP 5.6 repository
  apt_repository: repo='ppa:ondrej/php5-5.6'

- name: Installation
  apt: "pkg={{ item }} state=present update_cache=yes cache_valid_time=86400"
  with_items: php_packages
  notify: Restart php-fpm

- name: Place common config
  copy: "src={{ php_ini_file }} dest={{ php_ini_dir }}/{{ item }}/php.ini"
  with_items:
    - cli
    - fpm
  notify: Restart php-fpm

- name: Place fpm config
  template: "src=php-fpm.conf.j2 dest={{ php_ini_dir }}/fpm/pool.d/www.conf"
  notify: Restart php-fpm
