---
- name: Installation
  apt: "pkg={{ item }} state=present update_cache=yes cache_valid_time=86400"
  with_items: php_packages
  notify: Restart php-fpm

- name: Place common config
  template: src=php.ini.j2 dest=/etc/php5/{{ item }}/php.ini
  with_items:
    - cli
    - fpm
  notify: Restart php-fpm

- name: Enable mcrypt module
  shell: php5enmod mcrypt
  when: "'php5-mcrypt' in php_packages"
