---
- name: Creating users
  user: "name={{ item.name }} state=present shell=/bin/bash"
  with_items: "{{ users_list }}"

- name: Authorize access
  authorized_key: "user={{ item.name }} key='{{ lookup('file', item.authorized) }}'"
  with_items: "{{ users_list }}"
